language: generic

os:
  - linux
  - osx

dist: trusty
sudo: required

install:
  # Install dependencies
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo add-apt-repository ppa:haxe/ocaml -y;
      sudo apt-get update -qq;
      sudo apt-get install ocaml zlib1g-dev aspcud -qqy;
      wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin system;
      export OPAMYES=1;
      eval `opam config env`;
      opam install extlib ocamlfind;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      travis_retry brew update;
      travis_retry brew install opam;
      export OPAMYES=1;
      opam init;
      eval `opam config env`;
      opam install extlib ocamlfind;
    fi

script:
  - make
