variables:
  - group: variables-haxe
  - name: AZURE_PIPELINES_REPO_URL
    value: $(Build.Repository.Uri)
  - name: AZURE_PIPELINES_BRANCH
    value: $(Build.SourceBranchName)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

stages:
  - stage: StageTest
    jobs:
      - template: extra/azure-pipelines/build-linux.yml
        parameters:
          name: BuildLinux

      - template: extra/azure-pipelines/build-mac.yml
        parameters:
          name: BuildMac

      - template: extra/azure-pipelines/build-windows.yml
        parameters:
          name: BuildWin64
          arch: '64'

      - template: extra/azure-pipelines/build-windows.yml
        parameters:
          name: BuildWin32
          arch: '32'

      - job: TestLinux
        dependsOn: BuildLinux
        pool:
          vmImage: 'ubuntu-16.04'
        strategy:
          matrix:
            macro:
              TEST: macro
            neko:
              TEST: neko
            hl:
              TEST: hl
              APT_PACKAGES: cmake ninja-build
            cpp:
              TEST: cpp
              HXCPP_COMPILE_CACHE: ~/hxcache
              APT_PACKAGES: gcc-multilib g++-multilib
            java:
              TEST: java,jvm
            cs:
              TEST: cs
            js:
              TEST: js
              SAUCE_TUNNEL_ID: $(Agent.JobName)
              SAUCE_BUILD: $(Build.BuildNumber)
            php:
              TEST: php
            flash:
              TEST: flash9
              APT_PACKAGES: libglib2.0 libfreetype6 xvfb
              DISPLAY: ':99.0'
              AUDIODEV: 'null'
            python:
              TEST: python
            lua:
              TEST: lua
              APT_PACKAGES: ncurses-dev
        steps:
          - checkout: self
            fetchDepth: 20
          - template: extra/azure-pipelines/install-neko-snapshot.yaml
            parameters:
              platform: linux64
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'linuxBinaries'
              targetPath: linuxBinaries
          - script: |
              set -ex
              tar -xf linuxBinaries/*_bin.tar.gz -C linuxBinaries --strip-components=1
              sudo mkdir -p /usr/local/bin/
              sudo mkdir -p /usr/local/share/haxe/
              sudo ln -s `pwd`/linuxBinaries/haxe /usr/local/bin/haxe
              sudo ln -s `pwd`/linuxBinaries/haxelib /usr/local/bin/haxelib
              sudo ln -s `pwd`/linuxBinaries/std /usr/local/share/haxe/std
            displayName: Setup Haxe
          - script: haxe -version
            displayName: Print Haxe version
          - script: |
              set -ex
              mkdir ~/haxelib
              haxelib setup ~/haxelib
            displayName: Setup haxelib
          - script: |
              set -ex
              sudo apt update -qqy
              sudo apt install -qqy $APT_PACKAGES
            condition: and(succeeded(), variables['APT_PACKAGES'])
            displayName: Install apt packages
          - script: haxe RunCi.hxml
            condition: and(succeeded(), not(and(variables['SAUCE'], variables['SAUCE_ACCESS_KEY'])))
            workingDirectory: $(Build.SourcesDirectory)/tests
            displayName: Test
          - script: haxe RunCi.hxml
            condition: and(succeeded(), variables['SAUCE'], variables['SAUCE_ACCESS_KEY'])
            workingDirectory: $(Build.SourcesDirectory)/tests
            env:
              SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
            displayName: Test (with SauceLabs)

      - job: TestMac
        dependsOn: BuildMac
        pool:
          vmImage: 'macOS-10.14'
        strategy:
          matrix:
            macro:
              TEST: macro
            neko:
              TEST: neko
            hl:
              TEST: hl
              BREW_PACKAGES: ninja
            cpp:
              TEST: cpp
              HXCPP_COMPILE_CACHE: ~/hxcache
            java:
              TEST: java,jvm
            cs:
              TEST: cs
            js:
              TEST: js
            php:
              TEST: php
            flash:
              TEST: flash9
            python:
              TEST: python
            lua:
              TEST: lua
        steps:
          - checkout: self
            fetchDepth: 20
          - template: extra/azure-pipelines/install-neko-snapshot.yaml
            parameters:
              platform: mac
          - task: DownloadPipelineArtifact@0
            inputs:
              artifactName: 'macBinaries'
              targetPath: macBinaries
          - script: |
              set -ex
              tar -xf macBinaries/*_bin.tar.gz -C macBinaries --strip-components=1
              sudo mkdir -p /usr/local/bin/
              sudo mkdir -p /usr/local/share/haxe/
              sudo ln -s `pwd`/macBinaries/haxe /usr/local/bin/haxe
              sudo ln -s `pwd`/macBinaries/haxelib /usr/local/bin/haxelib
              sudo ln -s `pwd`/macBinaries/std /usr/local/share/haxe/std
            displayName: Setup Haxe
          - script: haxe -version
            displayName: Print Haxe version
          - script: |
              set -ex
              mkdir ~/haxelib
              haxelib setup ~/haxelib
            displayName: Setup haxelib
          - script: brew install $BREW_PACKAGES
            condition: and(succeeded(), variables['BREW_PACKAGES'])
            displayName: Install homebrew packages
          - script: |
              # disable invalid Unicode filenames on APFS
              echo "" > sys/compile-fs.hxml
              haxe RunCi.hxml
            workingDirectory: $(Build.SourcesDirectory)/tests
            displayName: Test

      - template: extra/azure-pipelines/test-windows.yml
        parameters:
          name: TestWin64
          arch: '64'

      - template: extra/azure-pipelines/test-windows.yml
        parameters:
          name: TestWin32
          arch: '32'
